// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uGrpc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "uGrpc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace uGrpc {
class UArgsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<UArgs> {
} _UArgs_default_instance_;
class UResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<UResponse> {
} _UResponse_default_instance_;
class EmbUArgsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<EmbUArgs> {
} _EmbUArgs_default_instance_;
class EmbUResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<EmbUResponse> {
} _EmbUResponse_default_instance_;

namespace protobuf_uGrpc_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[4];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, i32_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, i64_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, ui32_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, ui64_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, si32_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, si64_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, dble_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, flt_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, bl_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, str_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UArgs, bs_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, i32_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, i64_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, ui32_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, ui64_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, si32_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, si64_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, dble_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, flt_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, bl_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, str_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, bs_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UResponse, uargs_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmbUArgs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmbUArgs, lo_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmbUArgs, hi_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmbUResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmbUResponse, lo_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmbUResponse, hi_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(UArgs)},
  { 16, -1, sizeof(UResponse)},
  { 33, -1, sizeof(EmbUArgs)},
  { 40, -1, sizeof(EmbUResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_UArgs_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_UResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_EmbUArgs_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_EmbUResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "uGrpc.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

}  // namespace

void TableStruct::Shutdown() {
  _UArgs_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _UResponse_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _EmbUArgs_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _EmbUResponse_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _UArgs_default_instance_.DefaultConstruct();
  _UResponse_default_instance_.DefaultConstruct();
  _EmbUArgs_default_instance_.DefaultConstruct();
  _EmbUResponse_default_instance_.DefaultConstruct();
  _UResponse_default_instance_.get_mutable()->uargs_ = const_cast< ::uGrpc::UArgs*>(
      ::uGrpc::UArgs::internal_default_instance());
  _EmbUArgs_default_instance_.get_mutable()->lo_ = const_cast< ::uGrpc::UArgs*>(
      ::uGrpc::UArgs::internal_default_instance());
  _EmbUArgs_default_instance_.get_mutable()->hi_ = const_cast< ::uGrpc::UArgs*>(
      ::uGrpc::UArgs::internal_default_instance());
  _EmbUResponse_default_instance_.get_mutable()->lo_ = const_cast< ::uGrpc::UArgs*>(
      ::uGrpc::UArgs::internal_default_instance());
  _EmbUResponse_default_instance_.get_mutable()->hi_ = const_cast< ::uGrpc::UArgs*>(
      ::uGrpc::UArgs::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\013uGrpc.proto\022\005uGrpc\"\231\001\n\005UArgs\022\013\n\003i32\030\001 "
      "\001(\005\022\013\n\003i64\030\002 \001(\003\022\014\n\004ui32\030\003 \001(\r\022\014\n\004ui64\030\004"
      " \001(\004\022\014\n\004si32\030\005 \001(\021\022\014\n\004si64\030\006 \001(\022\022\014\n\004dble"
      "\030\007 \001(\001\022\013\n\003flt\030\010 \001(\002\022\n\n\002bl\030\t \001(\010\022\013\n\003str\030\n"
      " \001(\t\022\n\n\002bS\030\013 \001(\014\"\272\001\n\tUResponse\022\013\n\003i32\030\001 "
      "\001(\005\022\013\n\003i64\030\002 \001(\003\022\014\n\004ui32\030\003 \001(\r\022\014\n\004ui64\030\004"
      " \001(\004\022\014\n\004si32\030\005 \001(\021\022\014\n\004si64\030\006 \001(\022\022\014\n\004dble"
      "\030\007 \001(\001\022\013\n\003flt\030\010 \001(\002\022\n\n\002bl\030\t \001(\010\022\013\n\003str\030\n"
      " \001(\t\022\n\n\002bS\030\013 \001(\014\022\033\n\005uArgs\030\014 \001(\0132\014.uGrpc."
      "UArgs\">\n\010EmbUArgs\022\030\n\002lo\030\001 \001(\0132\014.uGrpc.UA"
      "rgs\022\030\n\002hi\030\002 \001(\0132\014.uGrpc.UArgs\"B\n\014EmbURes"
      "ponse\022\030\n\002lo\030\001 \001(\0132\014.uGrpc.UArgs\022\030\n\002hi\030\002 "
      "\001(\0132\014.uGrpc.UArgs2\344\001\n\005UGrpc\0220\n\014GetURespo"
      "nse\022\014.uGrpc.UArgs\032\020.uGrpc.UResponse\"\000\0227\n"
      "\016ListUResponses\022\017.uGrpc.EmbUArgs\032\020.uGrpc"
      ".UResponse\"\0000\001\0227\n\013RecordRoute\022\017.uGrpc.Em"
      "bUArgs\032\023.uGrpc.EmbUResponse\"\000(\001\0227\n\tRoute"
      "Chat\022\017.uGrpc.EmbUArgs\032\023.uGrpc.EmbURespon"
      "se\"\000(\0010\001B1\n\031falconray.u4go.gRPC.uGrpcB\nu"
      "GrpcProtoP\001\242\002\005UGRPCb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 787);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "uGrpc.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_uGrpc_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UArgs::kI32FieldNumber;
const int UArgs::kI64FieldNumber;
const int UArgs::kUi32FieldNumber;
const int UArgs::kUi64FieldNumber;
const int UArgs::kSi32FieldNumber;
const int UArgs::kSi64FieldNumber;
const int UArgs::kDbleFieldNumber;
const int UArgs::kFltFieldNumber;
const int UArgs::kBlFieldNumber;
const int UArgs::kStrFieldNumber;
const int UArgs::kBSFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UArgs::UArgs()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_uGrpc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:uGrpc.UArgs)
}
UArgs::UArgs(const UArgs& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.str().size() > 0) {
    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  bs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bs().size() > 0) {
    bs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bs_);
  }
  ::memcpy(&i64_, &from.i64_,
    reinterpret_cast<char*>(&bl_) -
    reinterpret_cast<char*>(&i64_) + sizeof(bl_));
  // @@protoc_insertion_point(copy_constructor:uGrpc.UArgs)
}

void UArgs::SharedCtor() {
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&i64_, 0, reinterpret_cast<char*>(&bl_) -
    reinterpret_cast<char*>(&i64_) + sizeof(bl_));
  _cached_size_ = 0;
}

UArgs::~UArgs() {
  // @@protoc_insertion_point(destructor:uGrpc.UArgs)
  SharedDtor();
}

void UArgs::SharedDtor() {
  str_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UArgs::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UArgs::descriptor() {
  protobuf_uGrpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_uGrpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UArgs& UArgs::default_instance() {
  protobuf_uGrpc_2eproto::InitDefaults();
  return *internal_default_instance();
}

UArgs* UArgs::New(::google::protobuf::Arena* arena) const {
  UArgs* n = new UArgs;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:uGrpc.UArgs)
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&i64_, 0, reinterpret_cast<char*>(&bl_) -
    reinterpret_cast<char*>(&i64_) + sizeof(bl_));
}

bool UArgs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:uGrpc.UArgs)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 i32 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &i32_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 i64 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &i64_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 ui32 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ui32_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 ui64 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &ui64_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 si32 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &si32_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint64 si64 = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &si64_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double dble = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dble_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float flt = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(69u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &flt_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool bl = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &bl_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string str = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_str()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->str().data(), this->str().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "uGrpc.UArgs.str"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes bS = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:uGrpc.UArgs)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:uGrpc.UArgs)
  return false;
#undef DO_
}

void UArgs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:uGrpc.UArgs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 i32 = 1;
  if (this->i32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->i32(), output);
  }

  // int64 i64 = 2;
  if (this->i64() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->i64(), output);
  }

  // uint32 ui32 = 3;
  if (this->ui32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->ui32(), output);
  }

  // uint64 ui64 = 4;
  if (this->ui64() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->ui64(), output);
  }

  // sint32 si32 = 5;
  if (this->si32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(5, this->si32(), output);
  }

  // sint64 si64 = 6;
  if (this->si64() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(6, this->si64(), output);
  }

  // double dble = 7;
  if (this->dble() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->dble(), output);
  }

  // float flt = 8;
  if (this->flt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->flt(), output);
  }

  // bool bl = 9;
  if (this->bl() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->bl(), output);
  }

  // string str = 10;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), this->str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "uGrpc.UArgs.str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->str(), output);
  }

  // bytes bS = 11;
  if (this->bs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      11, this->bs(), output);
  }

  // @@protoc_insertion_point(serialize_end:uGrpc.UArgs)
}

::google::protobuf::uint8* UArgs::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:uGrpc.UArgs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 i32 = 1;
  if (this->i32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->i32(), target);
  }

  // int64 i64 = 2;
  if (this->i64() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->i64(), target);
  }

  // uint32 ui32 = 3;
  if (this->ui32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->ui32(), target);
  }

  // uint64 ui64 = 4;
  if (this->ui64() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->ui64(), target);
  }

  // sint32 si32 = 5;
  if (this->si32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(5, this->si32(), target);
  }

  // sint64 si64 = 6;
  if (this->si64() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt64ToArray(6, this->si64(), target);
  }

  // double dble = 7;
  if (this->dble() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->dble(), target);
  }

  // float flt = 8;
  if (this->flt() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->flt(), target);
  }

  // bool bl = 9;
  if (this->bl() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->bl(), target);
  }

  // string str = 10;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), this->str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "uGrpc.UArgs.str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->str(), target);
  }

  // bytes bS = 11;
  if (this->bs().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        11, this->bs(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:uGrpc.UArgs)
  return target;
}

size_t UArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:uGrpc.UArgs)
  size_t total_size = 0;

  // string str = 10;
  if (this->str().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->str());
  }

  // bytes bS = 11;
  if (this->bs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bs());
  }

  // int64 i64 = 2;
  if (this->i64() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->i64());
  }

  // int32 i32 = 1;
  if (this->i32() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->i32());
  }

  // uint32 ui32 = 3;
  if (this->ui32() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ui32());
  }

  // uint64 ui64 = 4;
  if (this->ui64() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->ui64());
  }

  // sint64 si64 = 6;
  if (this->si64() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt64Size(
        this->si64());
  }

  // sint32 si32 = 5;
  if (this->si32() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->si32());
  }

  // float flt = 8;
  if (this->flt() != 0) {
    total_size += 1 + 4;
  }

  // double dble = 7;
  if (this->dble() != 0) {
    total_size += 1 + 8;
  }

  // bool bl = 9;
  if (this->bl() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UArgs::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:uGrpc.UArgs)
  GOOGLE_DCHECK_NE(&from, this);
  const UArgs* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UArgs>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:uGrpc.UArgs)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:uGrpc.UArgs)
    MergeFrom(*source);
  }
}

void UArgs::MergeFrom(const UArgs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:uGrpc.UArgs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.str().size() > 0) {

    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  if (from.bs().size() > 0) {

    bs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bs_);
  }
  if (from.i64() != 0) {
    set_i64(from.i64());
  }
  if (from.i32() != 0) {
    set_i32(from.i32());
  }
  if (from.ui32() != 0) {
    set_ui32(from.ui32());
  }
  if (from.ui64() != 0) {
    set_ui64(from.ui64());
  }
  if (from.si64() != 0) {
    set_si64(from.si64());
  }
  if (from.si32() != 0) {
    set_si32(from.si32());
  }
  if (from.flt() != 0) {
    set_flt(from.flt());
  }
  if (from.dble() != 0) {
    set_dble(from.dble());
  }
  if (from.bl() != 0) {
    set_bl(from.bl());
  }
}

void UArgs::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:uGrpc.UArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UArgs::CopyFrom(const UArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uGrpc.UArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UArgs::IsInitialized() const {
  return true;
}

void UArgs::Swap(UArgs* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UArgs::InternalSwap(UArgs* other) {
  str_.Swap(&other->str_);
  bs_.Swap(&other->bs_);
  std::swap(i64_, other->i64_);
  std::swap(i32_, other->i32_);
  std::swap(ui32_, other->ui32_);
  std::swap(ui64_, other->ui64_);
  std::swap(si64_, other->si64_);
  std::swap(si32_, other->si32_);
  std::swap(flt_, other->flt_);
  std::swap(dble_, other->dble_);
  std::swap(bl_, other->bl_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UArgs::GetMetadata() const {
  protobuf_uGrpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_uGrpc_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UArgs

// int32 i32 = 1;
void UArgs::clear_i32() {
  i32_ = 0;
}
::google::protobuf::int32 UArgs::i32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.i32)
  return i32_;
}
void UArgs::set_i32(::google::protobuf::int32 value) {
  
  i32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.i32)
}

// int64 i64 = 2;
void UArgs::clear_i64() {
  i64_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 UArgs::i64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.i64)
  return i64_;
}
void UArgs::set_i64(::google::protobuf::int64 value) {
  
  i64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.i64)
}

// uint32 ui32 = 3;
void UArgs::clear_ui32() {
  ui32_ = 0u;
}
::google::protobuf::uint32 UArgs::ui32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.ui32)
  return ui32_;
}
void UArgs::set_ui32(::google::protobuf::uint32 value) {
  
  ui32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.ui32)
}

// uint64 ui64 = 4;
void UArgs::clear_ui64() {
  ui64_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 UArgs::ui64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.ui64)
  return ui64_;
}
void UArgs::set_ui64(::google::protobuf::uint64 value) {
  
  ui64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.ui64)
}

// sint32 si32 = 5;
void UArgs::clear_si32() {
  si32_ = 0;
}
::google::protobuf::int32 UArgs::si32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.si32)
  return si32_;
}
void UArgs::set_si32(::google::protobuf::int32 value) {
  
  si32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.si32)
}

// sint64 si64 = 6;
void UArgs::clear_si64() {
  si64_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 UArgs::si64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.si64)
  return si64_;
}
void UArgs::set_si64(::google::protobuf::int64 value) {
  
  si64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.si64)
}

// double dble = 7;
void UArgs::clear_dble() {
  dble_ = 0;
}
double UArgs::dble() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.dble)
  return dble_;
}
void UArgs::set_dble(double value) {
  
  dble_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.dble)
}

// float flt = 8;
void UArgs::clear_flt() {
  flt_ = 0;
}
float UArgs::flt() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.flt)
  return flt_;
}
void UArgs::set_flt(float value) {
  
  flt_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.flt)
}

// bool bl = 9;
void UArgs::clear_bl() {
  bl_ = false;
}
bool UArgs::bl() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.bl)
  return bl_;
}
void UArgs::set_bl(bool value) {
  
  bl_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.bl)
}

// string str = 10;
void UArgs::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& UArgs::str() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.str)
  return str_.GetNoArena();
}
void UArgs::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.str)
}
#if LANG_CXX11
void UArgs::set_str(::std::string&& value) {
  
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:uGrpc.UArgs.str)
}
#endif
void UArgs::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:uGrpc.UArgs.str)
}
void UArgs::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:uGrpc.UArgs.str)
}
::std::string* UArgs::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:uGrpc.UArgs.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* UArgs::release_str() {
  // @@protoc_insertion_point(field_release:uGrpc.UArgs.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UArgs::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UArgs.str)
}

// bytes bS = 11;
void UArgs::clear_bs() {
  bs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& UArgs::bs() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.bS)
  return bs_.GetNoArena();
}
void UArgs::set_bs(const ::std::string& value) {
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.bS)
}
#if LANG_CXX11
void UArgs::set_bs(::std::string&& value) {
  
  bs_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:uGrpc.UArgs.bS)
}
#endif
void UArgs::set_bs(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:uGrpc.UArgs.bS)
}
void UArgs::set_bs(const void* value, size_t size) {
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:uGrpc.UArgs.bS)
}
::std::string* UArgs::mutable_bs() {
  
  // @@protoc_insertion_point(field_mutable:uGrpc.UArgs.bS)
  return bs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* UArgs::release_bs() {
  // @@protoc_insertion_point(field_release:uGrpc.UArgs.bS)
  
  return bs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UArgs::set_allocated_bs(::std::string* bs) {
  if (bs != NULL) {
    
  } else {
    
  }
  bs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bs);
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UArgs.bS)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UResponse::kI32FieldNumber;
const int UResponse::kI64FieldNumber;
const int UResponse::kUi32FieldNumber;
const int UResponse::kUi64FieldNumber;
const int UResponse::kSi32FieldNumber;
const int UResponse::kSi64FieldNumber;
const int UResponse::kDbleFieldNumber;
const int UResponse::kFltFieldNumber;
const int UResponse::kBlFieldNumber;
const int UResponse::kStrFieldNumber;
const int UResponse::kBSFieldNumber;
const int UResponse::kUArgsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UResponse::UResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_uGrpc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:uGrpc.UResponse)
}
UResponse::UResponse(const UResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.str().size() > 0) {
    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  bs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bs().size() > 0) {
    bs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bs_);
  }
  if (from.has_uargs()) {
    uargs_ = new ::uGrpc::UArgs(*from.uargs_);
  } else {
    uargs_ = NULL;
  }
  ::memcpy(&i64_, &from.i64_,
    reinterpret_cast<char*>(&bl_) -
    reinterpret_cast<char*>(&i64_) + sizeof(bl_));
  // @@protoc_insertion_point(copy_constructor:uGrpc.UResponse)
}

void UResponse::SharedCtor() {
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&uargs_, 0, reinterpret_cast<char*>(&bl_) -
    reinterpret_cast<char*>(&uargs_) + sizeof(bl_));
  _cached_size_ = 0;
}

UResponse::~UResponse() {
  // @@protoc_insertion_point(destructor:uGrpc.UResponse)
  SharedDtor();
}

void UResponse::SharedDtor() {
  str_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete uargs_;
  }
}

void UResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UResponse::descriptor() {
  protobuf_uGrpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_uGrpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UResponse& UResponse::default_instance() {
  protobuf_uGrpc_2eproto::InitDefaults();
  return *internal_default_instance();
}

UResponse* UResponse::New(::google::protobuf::Arena* arena) const {
  UResponse* n = new UResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:uGrpc.UResponse)
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && uargs_ != NULL) {
    delete uargs_;
  }
  uargs_ = NULL;
  ::memset(&i64_, 0, reinterpret_cast<char*>(&bl_) -
    reinterpret_cast<char*>(&i64_) + sizeof(bl_));
}

bool UResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:uGrpc.UResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 i32 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &i32_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 i64 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &i64_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 ui32 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ui32_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 ui64 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &ui64_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 si32 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &si32_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint64 si64 = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &si64_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double dble = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &dble_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float flt = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(69u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &flt_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool bl = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &bl_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string str = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_str()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->str().data(), this->str().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "uGrpc.UResponse.str"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes bS = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .uGrpc.UArgs uArgs = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_uargs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:uGrpc.UResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:uGrpc.UResponse)
  return false;
#undef DO_
}

void UResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:uGrpc.UResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 i32 = 1;
  if (this->i32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->i32(), output);
  }

  // int64 i64 = 2;
  if (this->i64() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->i64(), output);
  }

  // uint32 ui32 = 3;
  if (this->ui32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->ui32(), output);
  }

  // uint64 ui64 = 4;
  if (this->ui64() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->ui64(), output);
  }

  // sint32 si32 = 5;
  if (this->si32() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(5, this->si32(), output);
  }

  // sint64 si64 = 6;
  if (this->si64() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(6, this->si64(), output);
  }

  // double dble = 7;
  if (this->dble() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->dble(), output);
  }

  // float flt = 8;
  if (this->flt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->flt(), output);
  }

  // bool bl = 9;
  if (this->bl() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->bl(), output);
  }

  // string str = 10;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), this->str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "uGrpc.UResponse.str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->str(), output);
  }

  // bytes bS = 11;
  if (this->bs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      11, this->bs(), output);
  }

  // .uGrpc.UArgs uArgs = 12;
  if (this->has_uargs()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, *this->uargs_, output);
  }

  // @@protoc_insertion_point(serialize_end:uGrpc.UResponse)
}

::google::protobuf::uint8* UResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:uGrpc.UResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 i32 = 1;
  if (this->i32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->i32(), target);
  }

  // int64 i64 = 2;
  if (this->i64() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->i64(), target);
  }

  // uint32 ui32 = 3;
  if (this->ui32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->ui32(), target);
  }

  // uint64 ui64 = 4;
  if (this->ui64() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->ui64(), target);
  }

  // sint32 si32 = 5;
  if (this->si32() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(5, this->si32(), target);
  }

  // sint64 si64 = 6;
  if (this->si64() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt64ToArray(6, this->si64(), target);
  }

  // double dble = 7;
  if (this->dble() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->dble(), target);
  }

  // float flt = 8;
  if (this->flt() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->flt(), target);
  }

  // bool bl = 9;
  if (this->bl() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->bl(), target);
  }

  // string str = 10;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), this->str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "uGrpc.UResponse.str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->str(), target);
  }

  // bytes bS = 11;
  if (this->bs().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        11, this->bs(), target);
  }

  // .uGrpc.UArgs uArgs = 12;
  if (this->has_uargs()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        12, *this->uargs_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:uGrpc.UResponse)
  return target;
}

size_t UResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:uGrpc.UResponse)
  size_t total_size = 0;

  // string str = 10;
  if (this->str().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->str());
  }

  // bytes bS = 11;
  if (this->bs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bs());
  }

  // .uGrpc.UArgs uArgs = 12;
  if (this->has_uargs()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->uargs_);
  }

  // int64 i64 = 2;
  if (this->i64() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->i64());
  }

  // int32 i32 = 1;
  if (this->i32() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->i32());
  }

  // uint32 ui32 = 3;
  if (this->ui32() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ui32());
  }

  // uint64 ui64 = 4;
  if (this->ui64() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->ui64());
  }

  // sint64 si64 = 6;
  if (this->si64() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt64Size(
        this->si64());
  }

  // sint32 si32 = 5;
  if (this->si32() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->si32());
  }

  // float flt = 8;
  if (this->flt() != 0) {
    total_size += 1 + 4;
  }

  // double dble = 7;
  if (this->dble() != 0) {
    total_size += 1 + 8;
  }

  // bool bl = 9;
  if (this->bl() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:uGrpc.UResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const UResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:uGrpc.UResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:uGrpc.UResponse)
    MergeFrom(*source);
  }
}

void UResponse::MergeFrom(const UResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:uGrpc.UResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.str().size() > 0) {

    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  if (from.bs().size() > 0) {

    bs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bs_);
  }
  if (from.has_uargs()) {
    mutable_uargs()->::uGrpc::UArgs::MergeFrom(from.uargs());
  }
  if (from.i64() != 0) {
    set_i64(from.i64());
  }
  if (from.i32() != 0) {
    set_i32(from.i32());
  }
  if (from.ui32() != 0) {
    set_ui32(from.ui32());
  }
  if (from.ui64() != 0) {
    set_ui64(from.ui64());
  }
  if (from.si64() != 0) {
    set_si64(from.si64());
  }
  if (from.si32() != 0) {
    set_si32(from.si32());
  }
  if (from.flt() != 0) {
    set_flt(from.flt());
  }
  if (from.dble() != 0) {
    set_dble(from.dble());
  }
  if (from.bl() != 0) {
    set_bl(from.bl());
  }
}

void UResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:uGrpc.UResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UResponse::CopyFrom(const UResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uGrpc.UResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UResponse::IsInitialized() const {
  return true;
}

void UResponse::Swap(UResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UResponse::InternalSwap(UResponse* other) {
  str_.Swap(&other->str_);
  bs_.Swap(&other->bs_);
  std::swap(uargs_, other->uargs_);
  std::swap(i64_, other->i64_);
  std::swap(i32_, other->i32_);
  std::swap(ui32_, other->ui32_);
  std::swap(ui64_, other->ui64_);
  std::swap(si64_, other->si64_);
  std::swap(si32_, other->si32_);
  std::swap(flt_, other->flt_);
  std::swap(dble_, other->dble_);
  std::swap(bl_, other->bl_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UResponse::GetMetadata() const {
  protobuf_uGrpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_uGrpc_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UResponse

// int32 i32 = 1;
void UResponse::clear_i32() {
  i32_ = 0;
}
::google::protobuf::int32 UResponse::i32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.i32)
  return i32_;
}
void UResponse::set_i32(::google::protobuf::int32 value) {
  
  i32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.i32)
}

// int64 i64 = 2;
void UResponse::clear_i64() {
  i64_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 UResponse::i64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.i64)
  return i64_;
}
void UResponse::set_i64(::google::protobuf::int64 value) {
  
  i64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.i64)
}

// uint32 ui32 = 3;
void UResponse::clear_ui32() {
  ui32_ = 0u;
}
::google::protobuf::uint32 UResponse::ui32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.ui32)
  return ui32_;
}
void UResponse::set_ui32(::google::protobuf::uint32 value) {
  
  ui32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.ui32)
}

// uint64 ui64 = 4;
void UResponse::clear_ui64() {
  ui64_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 UResponse::ui64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.ui64)
  return ui64_;
}
void UResponse::set_ui64(::google::protobuf::uint64 value) {
  
  ui64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.ui64)
}

// sint32 si32 = 5;
void UResponse::clear_si32() {
  si32_ = 0;
}
::google::protobuf::int32 UResponse::si32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.si32)
  return si32_;
}
void UResponse::set_si32(::google::protobuf::int32 value) {
  
  si32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.si32)
}

// sint64 si64 = 6;
void UResponse::clear_si64() {
  si64_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 UResponse::si64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.si64)
  return si64_;
}
void UResponse::set_si64(::google::protobuf::int64 value) {
  
  si64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.si64)
}

// double dble = 7;
void UResponse::clear_dble() {
  dble_ = 0;
}
double UResponse::dble() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.dble)
  return dble_;
}
void UResponse::set_dble(double value) {
  
  dble_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.dble)
}

// float flt = 8;
void UResponse::clear_flt() {
  flt_ = 0;
}
float UResponse::flt() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.flt)
  return flt_;
}
void UResponse::set_flt(float value) {
  
  flt_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.flt)
}

// bool bl = 9;
void UResponse::clear_bl() {
  bl_ = false;
}
bool UResponse::bl() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.bl)
  return bl_;
}
void UResponse::set_bl(bool value) {
  
  bl_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.bl)
}

// string str = 10;
void UResponse::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& UResponse::str() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.str)
  return str_.GetNoArena();
}
void UResponse::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.str)
}
#if LANG_CXX11
void UResponse::set_str(::std::string&& value) {
  
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:uGrpc.UResponse.str)
}
#endif
void UResponse::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:uGrpc.UResponse.str)
}
void UResponse::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:uGrpc.UResponse.str)
}
::std::string* UResponse::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:uGrpc.UResponse.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* UResponse::release_str() {
  // @@protoc_insertion_point(field_release:uGrpc.UResponse.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UResponse::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UResponse.str)
}

// bytes bS = 11;
void UResponse::clear_bs() {
  bs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& UResponse::bs() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.bS)
  return bs_.GetNoArena();
}
void UResponse::set_bs(const ::std::string& value) {
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.bS)
}
#if LANG_CXX11
void UResponse::set_bs(::std::string&& value) {
  
  bs_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:uGrpc.UResponse.bS)
}
#endif
void UResponse::set_bs(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:uGrpc.UResponse.bS)
}
void UResponse::set_bs(const void* value, size_t size) {
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:uGrpc.UResponse.bS)
}
::std::string* UResponse::mutable_bs() {
  
  // @@protoc_insertion_point(field_mutable:uGrpc.UResponse.bS)
  return bs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* UResponse::release_bs() {
  // @@protoc_insertion_point(field_release:uGrpc.UResponse.bS)
  
  return bs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UResponse::set_allocated_bs(::std::string* bs) {
  if (bs != NULL) {
    
  } else {
    
  }
  bs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bs);
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UResponse.bS)
}

// .uGrpc.UArgs uArgs = 12;
bool UResponse::has_uargs() const {
  return this != internal_default_instance() && uargs_ != NULL;
}
void UResponse::clear_uargs() {
  if (GetArenaNoVirtual() == NULL && uargs_ != NULL) delete uargs_;
  uargs_ = NULL;
}
const ::uGrpc::UArgs& UResponse::uargs() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.uArgs)
  return uargs_ != NULL ? *uargs_
                         : *::uGrpc::UArgs::internal_default_instance();
}
::uGrpc::UArgs* UResponse::mutable_uargs() {
  
  if (uargs_ == NULL) {
    uargs_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.UResponse.uArgs)
  return uargs_;
}
::uGrpc::UArgs* UResponse::release_uargs() {
  // @@protoc_insertion_point(field_release:uGrpc.UResponse.uArgs)
  
  ::uGrpc::UArgs* temp = uargs_;
  uargs_ = NULL;
  return temp;
}
void UResponse::set_allocated_uargs(::uGrpc::UArgs* uargs) {
  delete uargs_;
  uargs_ = uargs;
  if (uargs) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UResponse.uArgs)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EmbUArgs::kLoFieldNumber;
const int EmbUArgs::kHiFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EmbUArgs::EmbUArgs()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_uGrpc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:uGrpc.EmbUArgs)
}
EmbUArgs::EmbUArgs(const EmbUArgs& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_lo()) {
    lo_ = new ::uGrpc::UArgs(*from.lo_);
  } else {
    lo_ = NULL;
  }
  if (from.has_hi()) {
    hi_ = new ::uGrpc::UArgs(*from.hi_);
  } else {
    hi_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:uGrpc.EmbUArgs)
}

void EmbUArgs::SharedCtor() {
  ::memset(&lo_, 0, reinterpret_cast<char*>(&hi_) -
    reinterpret_cast<char*>(&lo_) + sizeof(hi_));
  _cached_size_ = 0;
}

EmbUArgs::~EmbUArgs() {
  // @@protoc_insertion_point(destructor:uGrpc.EmbUArgs)
  SharedDtor();
}

void EmbUArgs::SharedDtor() {
  if (this != internal_default_instance()) {
    delete lo_;
  }
  if (this != internal_default_instance()) {
    delete hi_;
  }
}

void EmbUArgs::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EmbUArgs::descriptor() {
  protobuf_uGrpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_uGrpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EmbUArgs& EmbUArgs::default_instance() {
  protobuf_uGrpc_2eproto::InitDefaults();
  return *internal_default_instance();
}

EmbUArgs* EmbUArgs::New(::google::protobuf::Arena* arena) const {
  EmbUArgs* n = new EmbUArgs;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EmbUArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:uGrpc.EmbUArgs)
  if (GetArenaNoVirtual() == NULL && lo_ != NULL) {
    delete lo_;
  }
  lo_ = NULL;
  if (GetArenaNoVirtual() == NULL && hi_ != NULL) {
    delete hi_;
  }
  hi_ = NULL;
}

bool EmbUArgs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:uGrpc.EmbUArgs)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .uGrpc.UArgs lo = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_lo()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .uGrpc.UArgs hi = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_hi()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:uGrpc.EmbUArgs)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:uGrpc.EmbUArgs)
  return false;
#undef DO_
}

void EmbUArgs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:uGrpc.EmbUArgs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .uGrpc.UArgs lo = 1;
  if (this->has_lo()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->lo_, output);
  }

  // .uGrpc.UArgs hi = 2;
  if (this->has_hi()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->hi_, output);
  }

  // @@protoc_insertion_point(serialize_end:uGrpc.EmbUArgs)
}

::google::protobuf::uint8* EmbUArgs::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:uGrpc.EmbUArgs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .uGrpc.UArgs lo = 1;
  if (this->has_lo()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->lo_, deterministic, target);
  }

  // .uGrpc.UArgs hi = 2;
  if (this->has_hi()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->hi_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:uGrpc.EmbUArgs)
  return target;
}

size_t EmbUArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:uGrpc.EmbUArgs)
  size_t total_size = 0;

  // .uGrpc.UArgs lo = 1;
  if (this->has_lo()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->lo_);
  }

  // .uGrpc.UArgs hi = 2;
  if (this->has_hi()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->hi_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EmbUArgs::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:uGrpc.EmbUArgs)
  GOOGLE_DCHECK_NE(&from, this);
  const EmbUArgs* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EmbUArgs>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:uGrpc.EmbUArgs)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:uGrpc.EmbUArgs)
    MergeFrom(*source);
  }
}

void EmbUArgs::MergeFrom(const EmbUArgs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:uGrpc.EmbUArgs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_lo()) {
    mutable_lo()->::uGrpc::UArgs::MergeFrom(from.lo());
  }
  if (from.has_hi()) {
    mutable_hi()->::uGrpc::UArgs::MergeFrom(from.hi());
  }
}

void EmbUArgs::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:uGrpc.EmbUArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EmbUArgs::CopyFrom(const EmbUArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uGrpc.EmbUArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EmbUArgs::IsInitialized() const {
  return true;
}

void EmbUArgs::Swap(EmbUArgs* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EmbUArgs::InternalSwap(EmbUArgs* other) {
  std::swap(lo_, other->lo_);
  std::swap(hi_, other->hi_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EmbUArgs::GetMetadata() const {
  protobuf_uGrpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_uGrpc_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EmbUArgs

// .uGrpc.UArgs lo = 1;
bool EmbUArgs::has_lo() const {
  return this != internal_default_instance() && lo_ != NULL;
}
void EmbUArgs::clear_lo() {
  if (GetArenaNoVirtual() == NULL && lo_ != NULL) delete lo_;
  lo_ = NULL;
}
const ::uGrpc::UArgs& EmbUArgs::lo() const {
  // @@protoc_insertion_point(field_get:uGrpc.EmbUArgs.lo)
  return lo_ != NULL ? *lo_
                         : *::uGrpc::UArgs::internal_default_instance();
}
::uGrpc::UArgs* EmbUArgs::mutable_lo() {
  
  if (lo_ == NULL) {
    lo_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.EmbUArgs.lo)
  return lo_;
}
::uGrpc::UArgs* EmbUArgs::release_lo() {
  // @@protoc_insertion_point(field_release:uGrpc.EmbUArgs.lo)
  
  ::uGrpc::UArgs* temp = lo_;
  lo_ = NULL;
  return temp;
}
void EmbUArgs::set_allocated_lo(::uGrpc::UArgs* lo) {
  delete lo_;
  lo_ = lo;
  if (lo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.EmbUArgs.lo)
}

// .uGrpc.UArgs hi = 2;
bool EmbUArgs::has_hi() const {
  return this != internal_default_instance() && hi_ != NULL;
}
void EmbUArgs::clear_hi() {
  if (GetArenaNoVirtual() == NULL && hi_ != NULL) delete hi_;
  hi_ = NULL;
}
const ::uGrpc::UArgs& EmbUArgs::hi() const {
  // @@protoc_insertion_point(field_get:uGrpc.EmbUArgs.hi)
  return hi_ != NULL ? *hi_
                         : *::uGrpc::UArgs::internal_default_instance();
}
::uGrpc::UArgs* EmbUArgs::mutable_hi() {
  
  if (hi_ == NULL) {
    hi_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.EmbUArgs.hi)
  return hi_;
}
::uGrpc::UArgs* EmbUArgs::release_hi() {
  // @@protoc_insertion_point(field_release:uGrpc.EmbUArgs.hi)
  
  ::uGrpc::UArgs* temp = hi_;
  hi_ = NULL;
  return temp;
}
void EmbUArgs::set_allocated_hi(::uGrpc::UArgs* hi) {
  delete hi_;
  hi_ = hi;
  if (hi) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.EmbUArgs.hi)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EmbUResponse::kLoFieldNumber;
const int EmbUResponse::kHiFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EmbUResponse::EmbUResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_uGrpc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:uGrpc.EmbUResponse)
}
EmbUResponse::EmbUResponse(const EmbUResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_lo()) {
    lo_ = new ::uGrpc::UArgs(*from.lo_);
  } else {
    lo_ = NULL;
  }
  if (from.has_hi()) {
    hi_ = new ::uGrpc::UArgs(*from.hi_);
  } else {
    hi_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:uGrpc.EmbUResponse)
}

void EmbUResponse::SharedCtor() {
  ::memset(&lo_, 0, reinterpret_cast<char*>(&hi_) -
    reinterpret_cast<char*>(&lo_) + sizeof(hi_));
  _cached_size_ = 0;
}

EmbUResponse::~EmbUResponse() {
  // @@protoc_insertion_point(destructor:uGrpc.EmbUResponse)
  SharedDtor();
}

void EmbUResponse::SharedDtor() {
  if (this != internal_default_instance()) {
    delete lo_;
  }
  if (this != internal_default_instance()) {
    delete hi_;
  }
}

void EmbUResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EmbUResponse::descriptor() {
  protobuf_uGrpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_uGrpc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EmbUResponse& EmbUResponse::default_instance() {
  protobuf_uGrpc_2eproto::InitDefaults();
  return *internal_default_instance();
}

EmbUResponse* EmbUResponse::New(::google::protobuf::Arena* arena) const {
  EmbUResponse* n = new EmbUResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EmbUResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:uGrpc.EmbUResponse)
  if (GetArenaNoVirtual() == NULL && lo_ != NULL) {
    delete lo_;
  }
  lo_ = NULL;
  if (GetArenaNoVirtual() == NULL && hi_ != NULL) {
    delete hi_;
  }
  hi_ = NULL;
}

bool EmbUResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:uGrpc.EmbUResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .uGrpc.UArgs lo = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_lo()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .uGrpc.UArgs hi = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_hi()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:uGrpc.EmbUResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:uGrpc.EmbUResponse)
  return false;
#undef DO_
}

void EmbUResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:uGrpc.EmbUResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .uGrpc.UArgs lo = 1;
  if (this->has_lo()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->lo_, output);
  }

  // .uGrpc.UArgs hi = 2;
  if (this->has_hi()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->hi_, output);
  }

  // @@protoc_insertion_point(serialize_end:uGrpc.EmbUResponse)
}

::google::protobuf::uint8* EmbUResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:uGrpc.EmbUResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .uGrpc.UArgs lo = 1;
  if (this->has_lo()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->lo_, deterministic, target);
  }

  // .uGrpc.UArgs hi = 2;
  if (this->has_hi()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->hi_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:uGrpc.EmbUResponse)
  return target;
}

size_t EmbUResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:uGrpc.EmbUResponse)
  size_t total_size = 0;

  // .uGrpc.UArgs lo = 1;
  if (this->has_lo()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->lo_);
  }

  // .uGrpc.UArgs hi = 2;
  if (this->has_hi()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->hi_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EmbUResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:uGrpc.EmbUResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const EmbUResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EmbUResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:uGrpc.EmbUResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:uGrpc.EmbUResponse)
    MergeFrom(*source);
  }
}

void EmbUResponse::MergeFrom(const EmbUResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:uGrpc.EmbUResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_lo()) {
    mutable_lo()->::uGrpc::UArgs::MergeFrom(from.lo());
  }
  if (from.has_hi()) {
    mutable_hi()->::uGrpc::UArgs::MergeFrom(from.hi());
  }
}

void EmbUResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:uGrpc.EmbUResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EmbUResponse::CopyFrom(const EmbUResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uGrpc.EmbUResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EmbUResponse::IsInitialized() const {
  return true;
}

void EmbUResponse::Swap(EmbUResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EmbUResponse::InternalSwap(EmbUResponse* other) {
  std::swap(lo_, other->lo_);
  std::swap(hi_, other->hi_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EmbUResponse::GetMetadata() const {
  protobuf_uGrpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_uGrpc_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EmbUResponse

// .uGrpc.UArgs lo = 1;
bool EmbUResponse::has_lo() const {
  return this != internal_default_instance() && lo_ != NULL;
}
void EmbUResponse::clear_lo() {
  if (GetArenaNoVirtual() == NULL && lo_ != NULL) delete lo_;
  lo_ = NULL;
}
const ::uGrpc::UArgs& EmbUResponse::lo() const {
  // @@protoc_insertion_point(field_get:uGrpc.EmbUResponse.lo)
  return lo_ != NULL ? *lo_
                         : *::uGrpc::UArgs::internal_default_instance();
}
::uGrpc::UArgs* EmbUResponse::mutable_lo() {
  
  if (lo_ == NULL) {
    lo_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.EmbUResponse.lo)
  return lo_;
}
::uGrpc::UArgs* EmbUResponse::release_lo() {
  // @@protoc_insertion_point(field_release:uGrpc.EmbUResponse.lo)
  
  ::uGrpc::UArgs* temp = lo_;
  lo_ = NULL;
  return temp;
}
void EmbUResponse::set_allocated_lo(::uGrpc::UArgs* lo) {
  delete lo_;
  lo_ = lo;
  if (lo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.EmbUResponse.lo)
}

// .uGrpc.UArgs hi = 2;
bool EmbUResponse::has_hi() const {
  return this != internal_default_instance() && hi_ != NULL;
}
void EmbUResponse::clear_hi() {
  if (GetArenaNoVirtual() == NULL && hi_ != NULL) delete hi_;
  hi_ = NULL;
}
const ::uGrpc::UArgs& EmbUResponse::hi() const {
  // @@protoc_insertion_point(field_get:uGrpc.EmbUResponse.hi)
  return hi_ != NULL ? *hi_
                         : *::uGrpc::UArgs::internal_default_instance();
}
::uGrpc::UArgs* EmbUResponse::mutable_hi() {
  
  if (hi_ == NULL) {
    hi_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.EmbUResponse.hi)
  return hi_;
}
::uGrpc::UArgs* EmbUResponse::release_hi() {
  // @@protoc_insertion_point(field_release:uGrpc.EmbUResponse.hi)
  
  ::uGrpc::UArgs* temp = hi_;
  hi_ = NULL;
  return temp;
}
void EmbUResponse::set_allocated_hi(::uGrpc::UArgs* hi) {
  delete hi_;
  hi_ = hi;
  if (hi) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.EmbUResponse.hi)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace uGrpc

// @@protoc_insertion_point(global_scope)
