// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uGrpc.proto

#ifndef PROTOBUF_uGrpc_2eproto__INCLUDED
#define PROTOBUF_uGrpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace uGrpc {
class EmbUArgs;
class EmbUArgsDefaultTypeInternal;
extern EmbUArgsDefaultTypeInternal _EmbUArgs_default_instance_;
class EmbUResponse;
class EmbUResponseDefaultTypeInternal;
extern EmbUResponseDefaultTypeInternal _EmbUResponse_default_instance_;
class UArgs;
class UArgsDefaultTypeInternal;
extern UArgsDefaultTypeInternal _UArgs_default_instance_;
class UResponse;
class UResponseDefaultTypeInternal;
extern UResponseDefaultTypeInternal _UResponse_default_instance_;
}  // namespace uGrpc

namespace uGrpc {

namespace protobuf_uGrpc_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_uGrpc_2eproto

// ===================================================================

class UArgs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:uGrpc.UArgs) */ {
 public:
  UArgs();
  virtual ~UArgs();

  UArgs(const UArgs& from);

  inline UArgs& operator=(const UArgs& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UArgs& default_instance();

  static inline const UArgs* internal_default_instance() {
    return reinterpret_cast<const UArgs*>(
               &_UArgs_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(UArgs* other);

  // implements Message ----------------------------------------------

  inline UArgs* New() const PROTOBUF_FINAL { return New(NULL); }

  UArgs* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UArgs& from);
  void MergeFrom(const UArgs& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UArgs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string str = 10;
  void clear_str();
  static const int kStrFieldNumber = 10;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  #if LANG_CXX11
  void set_str(::std::string&& value);
  #endif
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // bytes bS = 11;
  void clear_bs();
  static const int kBSFieldNumber = 11;
  const ::std::string& bs() const;
  void set_bs(const ::std::string& value);
  #if LANG_CXX11
  void set_bs(::std::string&& value);
  #endif
  void set_bs(const char* value);
  void set_bs(const void* value, size_t size);
  ::std::string* mutable_bs();
  ::std::string* release_bs();
  void set_allocated_bs(::std::string* bs);

  // int64 i64 = 2;
  void clear_i64();
  static const int kI64FieldNumber = 2;
  ::google::protobuf::int64 i64() const;
  void set_i64(::google::protobuf::int64 value);

  // int32 i32 = 1;
  void clear_i32();
  static const int kI32FieldNumber = 1;
  ::google::protobuf::int32 i32() const;
  void set_i32(::google::protobuf::int32 value);

  // uint32 ui32 = 3;
  void clear_ui32();
  static const int kUi32FieldNumber = 3;
  ::google::protobuf::uint32 ui32() const;
  void set_ui32(::google::protobuf::uint32 value);

  // uint64 ui64 = 4;
  void clear_ui64();
  static const int kUi64FieldNumber = 4;
  ::google::protobuf::uint64 ui64() const;
  void set_ui64(::google::protobuf::uint64 value);

  // sint64 si64 = 6;
  void clear_si64();
  static const int kSi64FieldNumber = 6;
  ::google::protobuf::int64 si64() const;
  void set_si64(::google::protobuf::int64 value);

  // sint32 si32 = 5;
  void clear_si32();
  static const int kSi32FieldNumber = 5;
  ::google::protobuf::int32 si32() const;
  void set_si32(::google::protobuf::int32 value);

  // float flt = 8;
  void clear_flt();
  static const int kFltFieldNumber = 8;
  float flt() const;
  void set_flt(float value);

  // double dble = 7;
  void clear_dble();
  static const int kDbleFieldNumber = 7;
  double dble() const;
  void set_dble(double value);

  // bool bl = 9;
  void clear_bl();
  static const int kBlFieldNumber = 9;
  bool bl() const;
  void set_bl(bool value);

  // @@protoc_insertion_point(class_scope:uGrpc.UArgs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  ::google::protobuf::internal::ArenaStringPtr bs_;
  ::google::protobuf::int64 i64_;
  ::google::protobuf::int32 i32_;
  ::google::protobuf::uint32 ui32_;
  ::google::protobuf::uint64 ui64_;
  ::google::protobuf::int64 si64_;
  ::google::protobuf::int32 si32_;
  float flt_;
  double dble_;
  bool bl_;
  mutable int _cached_size_;
  friend struct protobuf_uGrpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:uGrpc.UResponse) */ {
 public:
  UResponse();
  virtual ~UResponse();

  UResponse(const UResponse& from);

  inline UResponse& operator=(const UResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UResponse& default_instance();

  static inline const UResponse* internal_default_instance() {
    return reinterpret_cast<const UResponse*>(
               &_UResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(UResponse* other);

  // implements Message ----------------------------------------------

  inline UResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  UResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UResponse& from);
  void MergeFrom(const UResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string str = 10;
  void clear_str();
  static const int kStrFieldNumber = 10;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  #if LANG_CXX11
  void set_str(::std::string&& value);
  #endif
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // bytes bS = 11;
  void clear_bs();
  static const int kBSFieldNumber = 11;
  const ::std::string& bs() const;
  void set_bs(const ::std::string& value);
  #if LANG_CXX11
  void set_bs(::std::string&& value);
  #endif
  void set_bs(const char* value);
  void set_bs(const void* value, size_t size);
  ::std::string* mutable_bs();
  ::std::string* release_bs();
  void set_allocated_bs(::std::string* bs);

  // .uGrpc.UArgs uArgs = 12;
  bool has_uargs() const;
  void clear_uargs();
  static const int kUArgsFieldNumber = 12;
  const ::uGrpc::UArgs& uargs() const;
  ::uGrpc::UArgs* mutable_uargs();
  ::uGrpc::UArgs* release_uargs();
  void set_allocated_uargs(::uGrpc::UArgs* uargs);

  // int64 i64 = 2;
  void clear_i64();
  static const int kI64FieldNumber = 2;
  ::google::protobuf::int64 i64() const;
  void set_i64(::google::protobuf::int64 value);

  // int32 i32 = 1;
  void clear_i32();
  static const int kI32FieldNumber = 1;
  ::google::protobuf::int32 i32() const;
  void set_i32(::google::protobuf::int32 value);

  // uint32 ui32 = 3;
  void clear_ui32();
  static const int kUi32FieldNumber = 3;
  ::google::protobuf::uint32 ui32() const;
  void set_ui32(::google::protobuf::uint32 value);

  // uint64 ui64 = 4;
  void clear_ui64();
  static const int kUi64FieldNumber = 4;
  ::google::protobuf::uint64 ui64() const;
  void set_ui64(::google::protobuf::uint64 value);

  // sint64 si64 = 6;
  void clear_si64();
  static const int kSi64FieldNumber = 6;
  ::google::protobuf::int64 si64() const;
  void set_si64(::google::protobuf::int64 value);

  // sint32 si32 = 5;
  void clear_si32();
  static const int kSi32FieldNumber = 5;
  ::google::protobuf::int32 si32() const;
  void set_si32(::google::protobuf::int32 value);

  // float flt = 8;
  void clear_flt();
  static const int kFltFieldNumber = 8;
  float flt() const;
  void set_flt(float value);

  // double dble = 7;
  void clear_dble();
  static const int kDbleFieldNumber = 7;
  double dble() const;
  void set_dble(double value);

  // bool bl = 9;
  void clear_bl();
  static const int kBlFieldNumber = 9;
  bool bl() const;
  void set_bl(bool value);

  // @@protoc_insertion_point(class_scope:uGrpc.UResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  ::google::protobuf::internal::ArenaStringPtr bs_;
  ::uGrpc::UArgs* uargs_;
  ::google::protobuf::int64 i64_;
  ::google::protobuf::int32 i32_;
  ::google::protobuf::uint32 ui32_;
  ::google::protobuf::uint64 ui64_;
  ::google::protobuf::int64 si64_;
  ::google::protobuf::int32 si32_;
  float flt_;
  double dble_;
  bool bl_;
  mutable int _cached_size_;
  friend struct protobuf_uGrpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EmbUArgs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:uGrpc.EmbUArgs) */ {
 public:
  EmbUArgs();
  virtual ~EmbUArgs();

  EmbUArgs(const EmbUArgs& from);

  inline EmbUArgs& operator=(const EmbUArgs& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EmbUArgs& default_instance();

  static inline const EmbUArgs* internal_default_instance() {
    return reinterpret_cast<const EmbUArgs*>(
               &_EmbUArgs_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(EmbUArgs* other);

  // implements Message ----------------------------------------------

  inline EmbUArgs* New() const PROTOBUF_FINAL { return New(NULL); }

  EmbUArgs* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const EmbUArgs& from);
  void MergeFrom(const EmbUArgs& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(EmbUArgs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .uGrpc.UArgs lo = 1;
  bool has_lo() const;
  void clear_lo();
  static const int kLoFieldNumber = 1;
  const ::uGrpc::UArgs& lo() const;
  ::uGrpc::UArgs* mutable_lo();
  ::uGrpc::UArgs* release_lo();
  void set_allocated_lo(::uGrpc::UArgs* lo);

  // .uGrpc.UArgs hi = 2;
  bool has_hi() const;
  void clear_hi();
  static const int kHiFieldNumber = 2;
  const ::uGrpc::UArgs& hi() const;
  ::uGrpc::UArgs* mutable_hi();
  ::uGrpc::UArgs* release_hi();
  void set_allocated_hi(::uGrpc::UArgs* hi);

  // @@protoc_insertion_point(class_scope:uGrpc.EmbUArgs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::uGrpc::UArgs* lo_;
  ::uGrpc::UArgs* hi_;
  mutable int _cached_size_;
  friend struct protobuf_uGrpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EmbUResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:uGrpc.EmbUResponse) */ {
 public:
  EmbUResponse();
  virtual ~EmbUResponse();

  EmbUResponse(const EmbUResponse& from);

  inline EmbUResponse& operator=(const EmbUResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EmbUResponse& default_instance();

  static inline const EmbUResponse* internal_default_instance() {
    return reinterpret_cast<const EmbUResponse*>(
               &_EmbUResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(EmbUResponse* other);

  // implements Message ----------------------------------------------

  inline EmbUResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  EmbUResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const EmbUResponse& from);
  void MergeFrom(const EmbUResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(EmbUResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .uGrpc.UArgs lo = 1;
  bool has_lo() const;
  void clear_lo();
  static const int kLoFieldNumber = 1;
  const ::uGrpc::UArgs& lo() const;
  ::uGrpc::UArgs* mutable_lo();
  ::uGrpc::UArgs* release_lo();
  void set_allocated_lo(::uGrpc::UArgs* lo);

  // .uGrpc.UArgs hi = 2;
  bool has_hi() const;
  void clear_hi();
  static const int kHiFieldNumber = 2;
  const ::uGrpc::UArgs& hi() const;
  ::uGrpc::UArgs* mutable_hi();
  ::uGrpc::UArgs* release_hi();
  void set_allocated_hi(::uGrpc::UArgs* hi);

  // @@protoc_insertion_point(class_scope:uGrpc.EmbUResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::uGrpc::UArgs* lo_;
  ::uGrpc::UArgs* hi_;
  mutable int _cached_size_;
  friend struct protobuf_uGrpc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UArgs

// int32 i32 = 1;
inline void UArgs::clear_i32() {
  i32_ = 0;
}
inline ::google::protobuf::int32 UArgs::i32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.i32)
  return i32_;
}
inline void UArgs::set_i32(::google::protobuf::int32 value) {
  
  i32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.i32)
}

// int64 i64 = 2;
inline void UArgs::clear_i64() {
  i64_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UArgs::i64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.i64)
  return i64_;
}
inline void UArgs::set_i64(::google::protobuf::int64 value) {
  
  i64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.i64)
}

// uint32 ui32 = 3;
inline void UArgs::clear_ui32() {
  ui32_ = 0u;
}
inline ::google::protobuf::uint32 UArgs::ui32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.ui32)
  return ui32_;
}
inline void UArgs::set_ui32(::google::protobuf::uint32 value) {
  
  ui32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.ui32)
}

// uint64 ui64 = 4;
inline void UArgs::clear_ui64() {
  ui64_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UArgs::ui64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.ui64)
  return ui64_;
}
inline void UArgs::set_ui64(::google::protobuf::uint64 value) {
  
  ui64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.ui64)
}

// sint32 si32 = 5;
inline void UArgs::clear_si32() {
  si32_ = 0;
}
inline ::google::protobuf::int32 UArgs::si32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.si32)
  return si32_;
}
inline void UArgs::set_si32(::google::protobuf::int32 value) {
  
  si32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.si32)
}

// sint64 si64 = 6;
inline void UArgs::clear_si64() {
  si64_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UArgs::si64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.si64)
  return si64_;
}
inline void UArgs::set_si64(::google::protobuf::int64 value) {
  
  si64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.si64)
}

// double dble = 7;
inline void UArgs::clear_dble() {
  dble_ = 0;
}
inline double UArgs::dble() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.dble)
  return dble_;
}
inline void UArgs::set_dble(double value) {
  
  dble_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.dble)
}

// float flt = 8;
inline void UArgs::clear_flt() {
  flt_ = 0;
}
inline float UArgs::flt() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.flt)
  return flt_;
}
inline void UArgs::set_flt(float value) {
  
  flt_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.flt)
}

// bool bl = 9;
inline void UArgs::clear_bl() {
  bl_ = false;
}
inline bool UArgs::bl() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.bl)
  return bl_;
}
inline void UArgs::set_bl(bool value) {
  
  bl_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.bl)
}

// string str = 10;
inline void UArgs::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UArgs::str() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.str)
  return str_.GetNoArena();
}
inline void UArgs::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.str)
}
#if LANG_CXX11
inline void UArgs::set_str(::std::string&& value) {
  
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:uGrpc.UArgs.str)
}
#endif
inline void UArgs::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:uGrpc.UArgs.str)
}
inline void UArgs::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:uGrpc.UArgs.str)
}
inline ::std::string* UArgs::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:uGrpc.UArgs.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UArgs::release_str() {
  // @@protoc_insertion_point(field_release:uGrpc.UArgs.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UArgs::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UArgs.str)
}

// bytes bS = 11;
inline void UArgs::clear_bs() {
  bs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UArgs::bs() const {
  // @@protoc_insertion_point(field_get:uGrpc.UArgs.bS)
  return bs_.GetNoArena();
}
inline void UArgs::set_bs(const ::std::string& value) {
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:uGrpc.UArgs.bS)
}
#if LANG_CXX11
inline void UArgs::set_bs(::std::string&& value) {
  
  bs_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:uGrpc.UArgs.bS)
}
#endif
inline void UArgs::set_bs(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:uGrpc.UArgs.bS)
}
inline void UArgs::set_bs(const void* value, size_t size) {
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:uGrpc.UArgs.bS)
}
inline ::std::string* UArgs::mutable_bs() {
  
  // @@protoc_insertion_point(field_mutable:uGrpc.UArgs.bS)
  return bs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UArgs::release_bs() {
  // @@protoc_insertion_point(field_release:uGrpc.UArgs.bS)
  
  return bs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UArgs::set_allocated_bs(::std::string* bs) {
  if (bs != NULL) {
    
  } else {
    
  }
  bs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bs);
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UArgs.bS)
}

// -------------------------------------------------------------------

// UResponse

// int32 i32 = 1;
inline void UResponse::clear_i32() {
  i32_ = 0;
}
inline ::google::protobuf::int32 UResponse::i32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.i32)
  return i32_;
}
inline void UResponse::set_i32(::google::protobuf::int32 value) {
  
  i32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.i32)
}

// int64 i64 = 2;
inline void UResponse::clear_i64() {
  i64_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UResponse::i64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.i64)
  return i64_;
}
inline void UResponse::set_i64(::google::protobuf::int64 value) {
  
  i64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.i64)
}

// uint32 ui32 = 3;
inline void UResponse::clear_ui32() {
  ui32_ = 0u;
}
inline ::google::protobuf::uint32 UResponse::ui32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.ui32)
  return ui32_;
}
inline void UResponse::set_ui32(::google::protobuf::uint32 value) {
  
  ui32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.ui32)
}

// uint64 ui64 = 4;
inline void UResponse::clear_ui64() {
  ui64_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UResponse::ui64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.ui64)
  return ui64_;
}
inline void UResponse::set_ui64(::google::protobuf::uint64 value) {
  
  ui64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.ui64)
}

// sint32 si32 = 5;
inline void UResponse::clear_si32() {
  si32_ = 0;
}
inline ::google::protobuf::int32 UResponse::si32() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.si32)
  return si32_;
}
inline void UResponse::set_si32(::google::protobuf::int32 value) {
  
  si32_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.si32)
}

// sint64 si64 = 6;
inline void UResponse::clear_si64() {
  si64_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UResponse::si64() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.si64)
  return si64_;
}
inline void UResponse::set_si64(::google::protobuf::int64 value) {
  
  si64_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.si64)
}

// double dble = 7;
inline void UResponse::clear_dble() {
  dble_ = 0;
}
inline double UResponse::dble() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.dble)
  return dble_;
}
inline void UResponse::set_dble(double value) {
  
  dble_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.dble)
}

// float flt = 8;
inline void UResponse::clear_flt() {
  flt_ = 0;
}
inline float UResponse::flt() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.flt)
  return flt_;
}
inline void UResponse::set_flt(float value) {
  
  flt_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.flt)
}

// bool bl = 9;
inline void UResponse::clear_bl() {
  bl_ = false;
}
inline bool UResponse::bl() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.bl)
  return bl_;
}
inline void UResponse::set_bl(bool value) {
  
  bl_ = value;
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.bl)
}

// string str = 10;
inline void UResponse::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UResponse::str() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.str)
  return str_.GetNoArena();
}
inline void UResponse::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.str)
}
#if LANG_CXX11
inline void UResponse::set_str(::std::string&& value) {
  
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:uGrpc.UResponse.str)
}
#endif
inline void UResponse::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:uGrpc.UResponse.str)
}
inline void UResponse::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:uGrpc.UResponse.str)
}
inline ::std::string* UResponse::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:uGrpc.UResponse.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UResponse::release_str() {
  // @@protoc_insertion_point(field_release:uGrpc.UResponse.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UResponse::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UResponse.str)
}

// bytes bS = 11;
inline void UResponse::clear_bs() {
  bs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UResponse::bs() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.bS)
  return bs_.GetNoArena();
}
inline void UResponse::set_bs(const ::std::string& value) {
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:uGrpc.UResponse.bS)
}
#if LANG_CXX11
inline void UResponse::set_bs(::std::string&& value) {
  
  bs_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:uGrpc.UResponse.bS)
}
#endif
inline void UResponse::set_bs(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:uGrpc.UResponse.bS)
}
inline void UResponse::set_bs(const void* value, size_t size) {
  
  bs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:uGrpc.UResponse.bS)
}
inline ::std::string* UResponse::mutable_bs() {
  
  // @@protoc_insertion_point(field_mutable:uGrpc.UResponse.bS)
  return bs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UResponse::release_bs() {
  // @@protoc_insertion_point(field_release:uGrpc.UResponse.bS)
  
  return bs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UResponse::set_allocated_bs(::std::string* bs) {
  if (bs != NULL) {
    
  } else {
    
  }
  bs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bs);
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UResponse.bS)
}

// .uGrpc.UArgs uArgs = 12;
inline bool UResponse::has_uargs() const {
  return this != internal_default_instance() && uargs_ != NULL;
}
inline void UResponse::clear_uargs() {
  if (GetArenaNoVirtual() == NULL && uargs_ != NULL) delete uargs_;
  uargs_ = NULL;
}
inline const ::uGrpc::UArgs& UResponse::uargs() const {
  // @@protoc_insertion_point(field_get:uGrpc.UResponse.uArgs)
  return uargs_ != NULL ? *uargs_
                         : *::uGrpc::UArgs::internal_default_instance();
}
inline ::uGrpc::UArgs* UResponse::mutable_uargs() {
  
  if (uargs_ == NULL) {
    uargs_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.UResponse.uArgs)
  return uargs_;
}
inline ::uGrpc::UArgs* UResponse::release_uargs() {
  // @@protoc_insertion_point(field_release:uGrpc.UResponse.uArgs)
  
  ::uGrpc::UArgs* temp = uargs_;
  uargs_ = NULL;
  return temp;
}
inline void UResponse::set_allocated_uargs(::uGrpc::UArgs* uargs) {
  delete uargs_;
  uargs_ = uargs;
  if (uargs) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.UResponse.uArgs)
}

// -------------------------------------------------------------------

// EmbUArgs

// .uGrpc.UArgs lo = 1;
inline bool EmbUArgs::has_lo() const {
  return this != internal_default_instance() && lo_ != NULL;
}
inline void EmbUArgs::clear_lo() {
  if (GetArenaNoVirtual() == NULL && lo_ != NULL) delete lo_;
  lo_ = NULL;
}
inline const ::uGrpc::UArgs& EmbUArgs::lo() const {
  // @@protoc_insertion_point(field_get:uGrpc.EmbUArgs.lo)
  return lo_ != NULL ? *lo_
                         : *::uGrpc::UArgs::internal_default_instance();
}
inline ::uGrpc::UArgs* EmbUArgs::mutable_lo() {
  
  if (lo_ == NULL) {
    lo_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.EmbUArgs.lo)
  return lo_;
}
inline ::uGrpc::UArgs* EmbUArgs::release_lo() {
  // @@protoc_insertion_point(field_release:uGrpc.EmbUArgs.lo)
  
  ::uGrpc::UArgs* temp = lo_;
  lo_ = NULL;
  return temp;
}
inline void EmbUArgs::set_allocated_lo(::uGrpc::UArgs* lo) {
  delete lo_;
  lo_ = lo;
  if (lo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.EmbUArgs.lo)
}

// .uGrpc.UArgs hi = 2;
inline bool EmbUArgs::has_hi() const {
  return this != internal_default_instance() && hi_ != NULL;
}
inline void EmbUArgs::clear_hi() {
  if (GetArenaNoVirtual() == NULL && hi_ != NULL) delete hi_;
  hi_ = NULL;
}
inline const ::uGrpc::UArgs& EmbUArgs::hi() const {
  // @@protoc_insertion_point(field_get:uGrpc.EmbUArgs.hi)
  return hi_ != NULL ? *hi_
                         : *::uGrpc::UArgs::internal_default_instance();
}
inline ::uGrpc::UArgs* EmbUArgs::mutable_hi() {
  
  if (hi_ == NULL) {
    hi_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.EmbUArgs.hi)
  return hi_;
}
inline ::uGrpc::UArgs* EmbUArgs::release_hi() {
  // @@protoc_insertion_point(field_release:uGrpc.EmbUArgs.hi)
  
  ::uGrpc::UArgs* temp = hi_;
  hi_ = NULL;
  return temp;
}
inline void EmbUArgs::set_allocated_hi(::uGrpc::UArgs* hi) {
  delete hi_;
  hi_ = hi;
  if (hi) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.EmbUArgs.hi)
}

// -------------------------------------------------------------------

// EmbUResponse

// .uGrpc.UArgs lo = 1;
inline bool EmbUResponse::has_lo() const {
  return this != internal_default_instance() && lo_ != NULL;
}
inline void EmbUResponse::clear_lo() {
  if (GetArenaNoVirtual() == NULL && lo_ != NULL) delete lo_;
  lo_ = NULL;
}
inline const ::uGrpc::UArgs& EmbUResponse::lo() const {
  // @@protoc_insertion_point(field_get:uGrpc.EmbUResponse.lo)
  return lo_ != NULL ? *lo_
                         : *::uGrpc::UArgs::internal_default_instance();
}
inline ::uGrpc::UArgs* EmbUResponse::mutable_lo() {
  
  if (lo_ == NULL) {
    lo_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.EmbUResponse.lo)
  return lo_;
}
inline ::uGrpc::UArgs* EmbUResponse::release_lo() {
  // @@protoc_insertion_point(field_release:uGrpc.EmbUResponse.lo)
  
  ::uGrpc::UArgs* temp = lo_;
  lo_ = NULL;
  return temp;
}
inline void EmbUResponse::set_allocated_lo(::uGrpc::UArgs* lo) {
  delete lo_;
  lo_ = lo;
  if (lo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.EmbUResponse.lo)
}

// .uGrpc.UArgs hi = 2;
inline bool EmbUResponse::has_hi() const {
  return this != internal_default_instance() && hi_ != NULL;
}
inline void EmbUResponse::clear_hi() {
  if (GetArenaNoVirtual() == NULL && hi_ != NULL) delete hi_;
  hi_ = NULL;
}
inline const ::uGrpc::UArgs& EmbUResponse::hi() const {
  // @@protoc_insertion_point(field_get:uGrpc.EmbUResponse.hi)
  return hi_ != NULL ? *hi_
                         : *::uGrpc::UArgs::internal_default_instance();
}
inline ::uGrpc::UArgs* EmbUResponse::mutable_hi() {
  
  if (hi_ == NULL) {
    hi_ = new ::uGrpc::UArgs;
  }
  // @@protoc_insertion_point(field_mutable:uGrpc.EmbUResponse.hi)
  return hi_;
}
inline ::uGrpc::UArgs* EmbUResponse::release_hi() {
  // @@protoc_insertion_point(field_release:uGrpc.EmbUResponse.hi)
  
  ::uGrpc::UArgs* temp = hi_;
  hi_ = NULL;
  return temp;
}
inline void EmbUResponse::set_allocated_hi(::uGrpc::UArgs* hi) {
  delete hi_;
  hi_ = hi;
  if (hi) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uGrpc.EmbUResponse.hi)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace uGrpc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_uGrpc_2eproto__INCLUDED
